<?php

namespace App\Database\Seeds;

use App\Models\Bookings;
use App\Models\Rooms;
use CodeIgniter\Database\Seeder;
use Illuminate\Support\Carbon;

class InitSeeder extends Seeder
{
    public function run()
    {
        Rooms::insert([
            [
                'name' => '01',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => '02',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => '03',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => '04',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => '05',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => '06',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => '07',
                'desc' => 'Deskripsi Kamar ...',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);

        // Bookings::insert([
        //     [
        //         'code' => 'A2024011800001',
        //         'room_id' => 1,
        //         'date_in' => Carbon::now()->addDays(1)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(3)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 1,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        //     [
        //         'code' => 'A2024011800002',
        //         'room_id' => 2,
        //         'date_in' => Carbon::now()->addDays(2)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(5)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 1,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        //     [
        //         'code' => 'A2024011800003',
        //         'room_id' => 3,
        //         'date_in' => Carbon::now()->addDays(1)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(2)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 0,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        //     [
        //         'code' => 'A2024011800004',
        //         'room_id' => 4,
        //         'date_in' => Carbon::now()->addDays(5)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(7)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 1,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        //     [
        //         'code' => 'A2024011800005',
        //         'room_id' => 5,
        //         'date_in' => Carbon::now()->addDays(1)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(1)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 1,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        //     [
        //         'code' => 'A2024011800006',
        //         'room_id' => 6,
        //         'date_in' => Carbon::now()->addDays(3)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(5)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 0,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        //     [
        //         'code' => 'A2024011800007',
        //         'room_id' => 7,
        //         'date_in' => Carbon::now()->addDays(8)->format('Y-m-d'),
        //         'date_out' => Carbon::now()->addDays(10)->format('Y-m-d'),
        //         'name' => 'Joko',
        //         'address' => 'Jl. Jalan',
        //         'phone' => '081234567890',
        //         'kk' => 'KK',
        //         'ktp' => 'KTP',
        //         'rujukan' => 'Rujukan',
        //         'bpjs' => 'BPJS',
        //         'pasfoto' => 'Pas Photo',
        //         'sktm' => 'SKTM',
        //         'status' => 1,
        //         'created_at' => date('Y-m-d H:i:s'),
        //         'updated_at' => date('Y-m-d H:i:s'),
        //     ],
        // ]);
    }
}
